### ISSUE TITLE
UI - Feat - Add user information in profile dropdown

### ISSUE THREAD

**Issue by MichaelWhitt** [MichaelWhitt/show-tracker#40]
## 📋 Task: 
- Add user name and email in profile dropdown, which comes back from the getUser API or Auth0.

### 📓 Description: 
- Click the profile image to see the dropdown modal.
- Find a way to add the user's name and email here; possibly need to widen the dropdown. This info comes back from the Auth0 api and also getUser api call. 

### :tada: Tidy Up
- [ ] My commits and PR title follow this format: fix or feat(scope or file): short description  [ fix(watched-items-list): change background color ]
- [ ] I checked that a component and util do not exist already that can be used in this task
- [ ] The console contains no new errors or warnings
- [ ] I have tested my code in the UI and am confident it functions

**Comment by aditya-10012002** [comment]
Let me do it.
